// Code generated by qtc from "base.page.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/base.page.qtpl:1
package templates

//line templates/base.page.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/base.page.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/base.page.qtpl:2
type Page interface {
//line templates/base.page.qtpl:2
	Title() string
//line templates/base.page.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
//line templates/base.page.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
//line templates/base.page.qtpl:2
	Description() string
//line templates/base.page.qtpl:2
	StreamDescription(qw422016 *qt422016.Writer)
//line templates/base.page.qtpl:2
	WriteDescription(qq422016 qtio422016.Writer)
//line templates/base.page.qtpl:2
	Body() string
//line templates/base.page.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
//line templates/base.page.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line templates/base.page.qtpl:2
	Stylesheet() string
//line templates/base.page.qtpl:2
	StreamStylesheet(qw422016 *qt422016.Writer)
//line templates/base.page.qtpl:2
	WriteStylesheet(qq422016 qtio422016.Writer)
//line templates/base.page.qtpl:2
	Script() string
//line templates/base.page.qtpl:2
	StreamScript(qw422016 *qt422016.Writer)
//line templates/base.page.qtpl:2
	WriteScript(qq422016 qtio422016.Writer)
//line templates/base.page.qtpl:2
	Domain() string
//line templates/base.page.qtpl:2
	StreamDomain(qw422016 *qt422016.Writer)
//line templates/base.page.qtpl:2
	WriteDomain(qq422016 qtio422016.Writer)
//line templates/base.page.qtpl:2
}

//line templates/base.page.qtpl:11
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line templates/base.page.qtpl:11
	qw422016.N().S(`
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="description" content="`)
//line templates/base.page.qtpl:16
	p.StreamDescription(qw422016)
//line templates/base.page.qtpl:16
	qw422016.N().S(`"/>
    <link rel="stylesheet" type="text/css" href="`)
//line templates/base.page.qtpl:17
	p.StreamDomain(qw422016)
//line templates/base.page.qtpl:17
	qw422016.N().S(`/`)
//line templates/base.page.qtpl:17
	p.StreamStylesheet(qw422016)
//line templates/base.page.qtpl:17
	qw422016.N().S(`">
    <title>`)
//line templates/base.page.qtpl:18
	p.StreamTitle(qw422016)
//line templates/base.page.qtpl:18
	qw422016.N().S(`</title>
</head>
<body>
`)
//line templates/base.page.qtpl:21
	p.StreamBody(qw422016)
//line templates/base.page.qtpl:21
	qw422016.N().S(`
<script type="text/javascript" src="`)
//line templates/base.page.qtpl:22
	p.StreamDomain(qw422016)
//line templates/base.page.qtpl:22
	qw422016.N().S(`/scripts/`)
//line templates/base.page.qtpl:22
	p.StreamScript(qw422016)
//line templates/base.page.qtpl:22
	qw422016.N().S(`"></script>
</body>
</html>
`)
//line templates/base.page.qtpl:25
}

//line templates/base.page.qtpl:25
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line templates/base.page.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.page.qtpl:25
	StreamPageTemplate(qw422016, p)
//line templates/base.page.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line templates/base.page.qtpl:25
}

//line templates/base.page.qtpl:25
func PageTemplate(p Page) string {
//line templates/base.page.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.page.qtpl:25
	WritePageTemplate(qb422016, p)
//line templates/base.page.qtpl:25
	qs422016 := string(qb422016.B)
//line templates/base.page.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.page.qtpl:25
	return qs422016
//line templates/base.page.qtpl:25
}

//line templates/base.page.qtpl:26
type BasePage struct{}

//line templates/base.page.qtpl:27
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/base.page.qtpl:27
}

//line templates/base.page.qtpl:27
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/base.page.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.page.qtpl:27
	p.StreamTitle(qw422016)
//line templates/base.page.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line templates/base.page.qtpl:27
}

//line templates/base.page.qtpl:27
func (p *BasePage) Title() string {
//line templates/base.page.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.page.qtpl:27
	p.WriteTitle(qb422016)
//line templates/base.page.qtpl:27
	qs422016 := string(qb422016.B)
//line templates/base.page.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.page.qtpl:27
	return qs422016
//line templates/base.page.qtpl:27
}

//line templates/base.page.qtpl:28
func (p *BasePage) StreamStylesheet(qw422016 *qt422016.Writer) {
//line templates/base.page.qtpl:28
}

//line templates/base.page.qtpl:28
func (p *BasePage) WriteStylesheet(qq422016 qtio422016.Writer) {
//line templates/base.page.qtpl:28
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.page.qtpl:28
	p.StreamStylesheet(qw422016)
//line templates/base.page.qtpl:28
	qt422016.ReleaseWriter(qw422016)
//line templates/base.page.qtpl:28
}

//line templates/base.page.qtpl:28
func (p *BasePage) Stylesheet() string {
//line templates/base.page.qtpl:28
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.page.qtpl:28
	p.WriteStylesheet(qb422016)
//line templates/base.page.qtpl:28
	qs422016 := string(qb422016.B)
//line templates/base.page.qtpl:28
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.page.qtpl:28
	return qs422016
//line templates/base.page.qtpl:28
}

//line templates/base.page.qtpl:29
func (p *BasePage) StreamScript(qw422016 *qt422016.Writer) {
//line templates/base.page.qtpl:29
}

//line templates/base.page.qtpl:29
func (p *BasePage) WriteScript(qq422016 qtio422016.Writer) {
//line templates/base.page.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.page.qtpl:29
	p.StreamScript(qw422016)
//line templates/base.page.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line templates/base.page.qtpl:29
}

//line templates/base.page.qtpl:29
func (p *BasePage) Script() string {
//line templates/base.page.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.page.qtpl:29
	p.WriteScript(qb422016)
//line templates/base.page.qtpl:29
	qs422016 := string(qb422016.B)
//line templates/base.page.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.page.qtpl:29
	return qs422016
//line templates/base.page.qtpl:29
}

//line templates/base.page.qtpl:30
func (p *BasePage) StreamDomain(qw422016 *qt422016.Writer) {
//line templates/base.page.qtpl:30
}

//line templates/base.page.qtpl:30
func (p *BasePage) WriteDomain(qq422016 qtio422016.Writer) {
//line templates/base.page.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.page.qtpl:30
	p.StreamDomain(qw422016)
//line templates/base.page.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line templates/base.page.qtpl:30
}

//line templates/base.page.qtpl:30
func (p *BasePage) Domain() string {
//line templates/base.page.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.page.qtpl:30
	p.WriteDomain(qb422016)
//line templates/base.page.qtpl:30
	qs422016 := string(qb422016.B)
//line templates/base.page.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.page.qtpl:30
	return qs422016
//line templates/base.page.qtpl:30
}

//line templates/base.page.qtpl:31
func (p *BasePage) StreamDescription(qw422016 *qt422016.Writer) {
//line templates/base.page.qtpl:31
	qw422016.N().S(`This is a base title`)
//line templates/base.page.qtpl:31
}

//line templates/base.page.qtpl:31
func (p *BasePage) WriteDescription(qq422016 qtio422016.Writer) {
//line templates/base.page.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.page.qtpl:31
	p.StreamDescription(qw422016)
//line templates/base.page.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line templates/base.page.qtpl:31
}

//line templates/base.page.qtpl:31
func (p *BasePage) Description() string {
//line templates/base.page.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.page.qtpl:31
	p.WriteDescription(qb422016)
//line templates/base.page.qtpl:31
	qs422016 := string(qb422016.B)
//line templates/base.page.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.page.qtpl:31
	return qs422016
//line templates/base.page.qtpl:31
}

//line templates/base.page.qtpl:32
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/base.page.qtpl:32
	qw422016.N().S(`This is a base body`)
//line templates/base.page.qtpl:32
}

//line templates/base.page.qtpl:32
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/base.page.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.page.qtpl:32
	p.StreamBody(qw422016)
//line templates/base.page.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line templates/base.page.qtpl:32
}

//line templates/base.page.qtpl:32
func (p *BasePage) Body() string {
//line templates/base.page.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.page.qtpl:32
	p.WriteBody(qb422016)
//line templates/base.page.qtpl:32
	qs422016 := string(qb422016.B)
//line templates/base.page.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.page.qtpl:32
	return qs422016
//line templates/base.page.qtpl:32
}
