// Code generated by qtc from "error.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/error.qtpl:1
package templates

//line templates/error.qtpl:1
import (
	"github.com/valyala/fasthttp"
)

//line templates/error.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/error.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/error.qtpl:7
type ErrorPage struct {
	CTX      *fasthttp.RequestCtx
	Message  string
	Solution string
	Js       string
	Css      string
	Host     string
}

//line templates/error.qtpl:17
func (view *ErrorPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/error.qtpl:17
	qw422016.N().S(`
<div class="view error-holder">
<div class="error">
    <div class="caption">Възникна грешка</div>
    <div class="content">
    <div class="message">`)
//line templates/error.qtpl:22
	qw422016.E().S(view.Message)
//line templates/error.qtpl:22
	qw422016.N().S(`</div>
    <div class="solution">`)
//line templates/error.qtpl:23
	qw422016.E().S(view.Solution)
//line templates/error.qtpl:23
	qw422016.N().S(`</div>
    </div>
</div>
</div>
`)
//line templates/error.qtpl:27
}

//line templates/error.qtpl:27
func (view *ErrorPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/error.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/error.qtpl:27
	view.StreamBody(qw422016)
//line templates/error.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line templates/error.qtpl:27
}

//line templates/error.qtpl:27
func (view *ErrorPage) Body() string {
//line templates/error.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/error.qtpl:27
	view.WriteBody(qb422016)
//line templates/error.qtpl:27
	qs422016 := string(qb422016.B)
//line templates/error.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/error.qtpl:27
	return qs422016
//line templates/error.qtpl:27
}

//line templates/error.qtpl:28
func (view *ErrorPage) StreamDescription(qw422016 *qt422016.Writer) {
//line templates/error.qtpl:28
	qw422016.N().S(`
`)
//line templates/error.qtpl:29
}

//line templates/error.qtpl:29
func (view *ErrorPage) WriteDescription(qq422016 qtio422016.Writer) {
//line templates/error.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/error.qtpl:29
	view.StreamDescription(qw422016)
//line templates/error.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line templates/error.qtpl:29
}

//line templates/error.qtpl:29
func (view *ErrorPage) Description() string {
//line templates/error.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/error.qtpl:29
	view.WriteDescription(qb422016)
//line templates/error.qtpl:29
	qs422016 := string(qb422016.B)
//line templates/error.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/error.qtpl:29
	return qs422016
//line templates/error.qtpl:29
}

//line templates/error.qtpl:30
func (view *ErrorPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/error.qtpl:30
	qw422016.N().S(`Възникна грешка`)
//line templates/error.qtpl:30
}

//line templates/error.qtpl:30
func (view *ErrorPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/error.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/error.qtpl:30
	view.StreamTitle(qw422016)
//line templates/error.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line templates/error.qtpl:30
}

//line templates/error.qtpl:30
func (view *ErrorPage) Title() string {
//line templates/error.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/error.qtpl:30
	view.WriteTitle(qb422016)
//line templates/error.qtpl:30
	qs422016 := string(qb422016.B)
//line templates/error.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/error.qtpl:30
	return qs422016
//line templates/error.qtpl:30
}

//line templates/error.qtpl:31
func (view *ErrorPage) StreamStylesheet(qw422016 *qt422016.Writer) {
//line templates/error.qtpl:31
	qw422016.E().S(view.Css)
//line templates/error.qtpl:31
}

//line templates/error.qtpl:31
func (view *ErrorPage) WriteStylesheet(qq422016 qtio422016.Writer) {
//line templates/error.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/error.qtpl:31
	view.StreamStylesheet(qw422016)
//line templates/error.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line templates/error.qtpl:31
}

//line templates/error.qtpl:31
func (view *ErrorPage) Stylesheet() string {
//line templates/error.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/error.qtpl:31
	view.WriteStylesheet(qb422016)
//line templates/error.qtpl:31
	qs422016 := string(qb422016.B)
//line templates/error.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/error.qtpl:31
	return qs422016
//line templates/error.qtpl:31
}

//line templates/error.qtpl:32
func (view *ErrorPage) StreamScript(qw422016 *qt422016.Writer) {
//line templates/error.qtpl:32
	qw422016.E().S(view.Js)
//line templates/error.qtpl:32
}

//line templates/error.qtpl:32
func (view *ErrorPage) WriteScript(qq422016 qtio422016.Writer) {
//line templates/error.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/error.qtpl:32
	view.StreamScript(qw422016)
//line templates/error.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line templates/error.qtpl:32
}

//line templates/error.qtpl:32
func (view *ErrorPage) Script() string {
//line templates/error.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/error.qtpl:32
	view.WriteScript(qb422016)
//line templates/error.qtpl:32
	qs422016 := string(qb422016.B)
//line templates/error.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/error.qtpl:32
	return qs422016
//line templates/error.qtpl:32
}

//line templates/error.qtpl:33
func (view *ErrorPage) StreamDomain(qw422016 *qt422016.Writer) {
//line templates/error.qtpl:33
	qw422016.E().S(view.Host)
//line templates/error.qtpl:33
}

//line templates/error.qtpl:33
func (view *ErrorPage) WriteDomain(qq422016 qtio422016.Writer) {
//line templates/error.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/error.qtpl:33
	view.StreamDomain(qw422016)
//line templates/error.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line templates/error.qtpl:33
}

//line templates/error.qtpl:33
func (view *ErrorPage) Domain() string {
//line templates/error.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/error.qtpl:33
	view.WriteDomain(qb422016)
//line templates/error.qtpl:33
	qs422016 := string(qb422016.B)
//line templates/error.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/error.qtpl:33
	return qs422016
//line templates/error.qtpl:33
}
