// Code generated by qtc from "task.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/task.qtpl:1
package templates

//line templates/task.qtpl:1
import (
	"github.com/valyala/fasthttp"
)

//line templates/task.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/task.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/task.qtpl:7
type TaskPage struct {
	CTX  *fasthttp.RequestCtx
	Js   string
	Css  string
	Host string
}

//line templates/task.qtpl:15
func (view *TaskPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/task.qtpl:15
	qw422016.N().S(`
<div style="margin:50px auto;width:900px;">

    <div style="margin:15px 0;">
        <div style="display: inline-block;vertical-align: top;width:50px;height:50px;border-radius:8px;border:1px solid #ccc; background-color: #fff;margin-right: 10px">

        </div>
        <div style="display: inline-block;vertical-align: top">
            <div style="font-weight: 600;font-size:18px;margin-top: 3px">URL Shortener</div>
            <div>Задача от Chaos за Николай Иванов</div>
        </div>
        <div style="float:right;display:flex;flex-direction: column">
            <a href="/"><div style="display: flex">
                <div style="background-color: #3F2D64;border-radius: 6px;width:25px;height:25px;line-height:  25px;   text-align: center;
 font-weight: bold;font-size:14px;color:#fff;">?
                </div>
                <div style="padding:3px 0 0 5px;">Ръководство на потребителя</div>


            </div></a>
            <a href="/tech-doc"><div style="display: flex;margin-top: 5px">
                <div style="background-color: #3F2D64;border-radius: 6px;width:25px;height:25px;line-height:  23px;   text-align: center;
 font-weight: bold;font-size:14px;color:#fff;">{&nbsp;}
                </div>
                <div style="padding:3px 0 0 5px;">Техническа документация</div>


                </div></a>
        </div>
    </div>
    <iframe src="/pdf/task-url-shortener.pdf" height="800" width="900"></iframe>


</div>
`)
//line templates/task.qtpl:49
}

//line templates/task.qtpl:49
func (view *TaskPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/task.qtpl:49
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/task.qtpl:49
	view.StreamBody(qw422016)
//line templates/task.qtpl:49
	qt422016.ReleaseWriter(qw422016)
//line templates/task.qtpl:49
}

//line templates/task.qtpl:49
func (view *TaskPage) Body() string {
//line templates/task.qtpl:49
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/task.qtpl:49
	view.WriteBody(qb422016)
//line templates/task.qtpl:49
	qs422016 := string(qb422016.B)
//line templates/task.qtpl:49
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/task.qtpl:49
	return qs422016
//line templates/task.qtpl:49
}

//line templates/task.qtpl:50
func (view *TaskPage) StreamDescription(qw422016 *qt422016.Writer) {
//line templates/task.qtpl:50
}

//line templates/task.qtpl:50
func (view *TaskPage) WriteDescription(qq422016 qtio422016.Writer) {
//line templates/task.qtpl:50
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/task.qtpl:50
	view.StreamDescription(qw422016)
//line templates/task.qtpl:50
	qt422016.ReleaseWriter(qw422016)
//line templates/task.qtpl:50
}

//line templates/task.qtpl:50
func (view *TaskPage) Description() string {
//line templates/task.qtpl:50
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/task.qtpl:50
	view.WriteDescription(qb422016)
//line templates/task.qtpl:50
	qs422016 := string(qb422016.B)
//line templates/task.qtpl:50
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/task.qtpl:50
	return qs422016
//line templates/task.qtpl:50
}

//line templates/task.qtpl:51
func (view *TaskPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/task.qtpl:51
}

//line templates/task.qtpl:51
func (view *TaskPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/task.qtpl:51
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/task.qtpl:51
	view.StreamTitle(qw422016)
//line templates/task.qtpl:51
	qt422016.ReleaseWriter(qw422016)
//line templates/task.qtpl:51
}

//line templates/task.qtpl:51
func (view *TaskPage) Title() string {
//line templates/task.qtpl:51
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/task.qtpl:51
	view.WriteTitle(qb422016)
//line templates/task.qtpl:51
	qs422016 := string(qb422016.B)
//line templates/task.qtpl:51
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/task.qtpl:51
	return qs422016
//line templates/task.qtpl:51
}

//line templates/task.qtpl:52
func (view *TaskPage) StreamStylesheet(qw422016 *qt422016.Writer) {
//line templates/task.qtpl:52
	qw422016.E().S(view.Css)
//line templates/task.qtpl:52
}

//line templates/task.qtpl:52
func (view *TaskPage) WriteStylesheet(qq422016 qtio422016.Writer) {
//line templates/task.qtpl:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/task.qtpl:52
	view.StreamStylesheet(qw422016)
//line templates/task.qtpl:52
	qt422016.ReleaseWriter(qw422016)
//line templates/task.qtpl:52
}

//line templates/task.qtpl:52
func (view *TaskPage) Stylesheet() string {
//line templates/task.qtpl:52
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/task.qtpl:52
	view.WriteStylesheet(qb422016)
//line templates/task.qtpl:52
	qs422016 := string(qb422016.B)
//line templates/task.qtpl:52
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/task.qtpl:52
	return qs422016
//line templates/task.qtpl:52
}

//line templates/task.qtpl:53
func (view *TaskPage) StreamScript(qw422016 *qt422016.Writer) {
//line templates/task.qtpl:53
	qw422016.E().S(view.Js)
//line templates/task.qtpl:53
}

//line templates/task.qtpl:53
func (view *TaskPage) WriteScript(qq422016 qtio422016.Writer) {
//line templates/task.qtpl:53
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/task.qtpl:53
	view.StreamScript(qw422016)
//line templates/task.qtpl:53
	qt422016.ReleaseWriter(qw422016)
//line templates/task.qtpl:53
}

//line templates/task.qtpl:53
func (view *TaskPage) Script() string {
//line templates/task.qtpl:53
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/task.qtpl:53
	view.WriteScript(qb422016)
//line templates/task.qtpl:53
	qs422016 := string(qb422016.B)
//line templates/task.qtpl:53
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/task.qtpl:53
	return qs422016
//line templates/task.qtpl:53
}

//line templates/task.qtpl:54
func (view *TaskPage) StreamDomain(qw422016 *qt422016.Writer) {
//line templates/task.qtpl:54
	qw422016.E().S(view.Host)
//line templates/task.qtpl:54
}

//line templates/task.qtpl:54
func (view *TaskPage) WriteDomain(qq422016 qtio422016.Writer) {
//line templates/task.qtpl:54
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/task.qtpl:54
	view.StreamDomain(qw422016)
//line templates/task.qtpl:54
	qt422016.ReleaseWriter(qw422016)
//line templates/task.qtpl:54
}

//line templates/task.qtpl:54
func (view *TaskPage) Domain() string {
//line templates/task.qtpl:54
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/task.qtpl:54
	view.WriteDomain(qb422016)
//line templates/task.qtpl:54
	qs422016 := string(qb422016.B)
//line templates/task.qtpl:54
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/task.qtpl:54
	return qs422016
//line templates/task.qtpl:54
}
